#!/bin/bash

# This script creates the compact.json file and the compact-cov-matrix.json file, execute this script after run-tacoco
# to be run from within the tacoco dir
# The command line arg descriptions are as follows: 
# NOTE do not include an ending backslash for any of the command line arg
# $1 command line arg, absolute path of system-under-test's root 
# $2 command line arg, refers to the name of the file/program that is going to be compacted
# $3 command line arg, refers to the absolute path file of the coverage-data-file 

mvn -q exec:java -Panalyzer -Dtacoco.sut=$1 -Dtacoco.json=${2}-compact.json -Dtacoco.exec=jacoco.exec -Dtacoco.pp -Dtacoco.fmt=COMPACT
echo ${2}-compact.json

FILEPATH=${3}/${2}-compact.json
echo $FILEPATH
mvn -q exec:java -Preader -Dtacoco.json="${FILEPATH}"


